global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'payment-gateway'
    static_configs:
      - targets: ['payment-gateway:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'provider-payment-mock'
    static_configs:
      - targets: ['provider-payment-mock:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
